// Code generated by protoc-gen-go.
// source: protocol.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	Test
	Person
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Test struct {
	Label string  `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	Type  int32   `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Reps  []int64 `protobuf:"varint,3,rep,packed,name=reps" json:"reps,omitempty"`
	Man   *Person `protobuf:"bytes,4,opt,name=man" json:"man,omitempty"`
}

func (m *Test) Reset()                    { *m = Test{} }
func (m *Test) String() string            { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()               {}
func (*Test) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Test) GetMan() *Person {
	if m != nil {
		return m.Man
	}
	return nil
}

type Person struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Test)(nil), "protocol.Test")
	proto.RegisterType((*Person)(nil), "protocol.Person")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x03, 0x33, 0x84, 0x38, 0x60, 0x7c, 0xa5, 0x0c, 0x2e, 0x96, 0x90,
	0xd4, 0xe2, 0x12, 0x21, 0x11, 0x2e, 0xd6, 0x9c, 0xc4, 0xa4, 0xd4, 0x1c, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0xce, 0x20, 0x08, 0x47, 0x48, 0x88, 0x8b, 0xa5, 0xa4, 0xb2, 0x20, 0x55, 0x82, 0x09, 0x28,
	0xc8, 0x1a, 0x04, 0x66, 0x83, 0xc4, 0x8a, 0x52, 0x0b, 0x8a, 0x25, 0x98, 0x15, 0x98, 0x35, 0x98,
	0x83, 0xc0, 0x6c, 0x21, 0x25, 0x2e, 0xe6, 0xdc, 0xc4, 0x3c, 0x09, 0x16, 0xa0, 0x32, 0x6e, 0x23,
	0x01, 0x3d, 0xb8, 0x6d, 0x01, 0xa9, 0x45, 0xc5, 0xf9, 0x79, 0x41, 0x20, 0x49, 0x25, 0x19, 0x2e,
	0x36, 0x08, 0x17, 0x64, 0x42, 0x5e, 0x62, 0x6e, 0x2a, 0xd4, 0x2a, 0x30, 0x3b, 0x89, 0x0d, 0xac,
	0xc7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x12, 0xc2, 0xca, 0x84, 0xaa, 0x00, 0x00, 0x00,
}
